name: Authenticity and Faith
favicon: null
layout_spectrum: 0.40562
typography_spectrum: 0.19150602002628148
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5c85b3'
    - '#395ea4'
    - '#e7e6ec'
    - '#1b1f12'
    - '#a9b3bf'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
